name: .NET Appium Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Android SDK and Emulator
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        mkdir -p $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        
        # Set Android environment variables
        echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export ANDROID_AVD_HOME=$HOME/.android/avd" >> $GITHUB_ENV
        echo "export PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$HOME/android-sdk/emulator:$PATH" >> $GITHUB_ENV
        source $GITHUB_ENV

        # Install missing emulator and other SDK components
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "emulator" "platforms;android-30" "system-images;android-30;default;x86_64"

        # Accept SDK licenses
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

        # Verify installation
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --list
        ls -la $HOME/android-sdk/emulator/

    - name: Create and Start Emulator
      run: |
        echo "Creating AVD..."
        mkdir -p $HOME/.android/avd
        echo "no" | $HOME/android-sdk/cmdline-tools/latest/bin/avdmanager create avd -n test_emulator -k "system-images;android-30;default;x86_64" --device "pixel_4"
        
        echo "Verifying AVD..."
        $HOME/android-sdk/emulator/emulator -list-avds

        echo "Starting Emulator..."
        nohup $HOME/android-sdk/emulator/emulator -avd test_emulator -no-snapshot -no-audio -no-window -gpu off &
        sleep 90  # Give time for emulator to start

    - name: Verify Emulator
      run: |
        $HOME/android-sdk/platform-tools/adb devices
        $HOME/android-sdk/emulator/emulator -list-avds

    - name: Install Appium and Dependencies
      run: |
        npm install -g appium
        appium -v
        npm install -g @appium/doctor
        appium-doctor

    - name: Start Appium Server
      run: |
        nohup appium > appium.log 2>&1 &
        sleep 10  # Give Appium time to start

    - name: Run Appium Tests
      env:
        APPIUM_HOST: "http://127.0.0.1:4723"
      run: dotnet test --no-build --verbosity normal --filter "TestCategory=TapFeature"
